services:
  - type: web
    name: telegram-mass-inviter-v1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: NODE_VERSION
        value: 18.16.0
    disk:
      name: bot-data
      mountPath: /app/data
      sizeGB: 1
