services:
  - type: web
    name: telegram-mass-inviter
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
